version: '3.9'

services:
  db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: 'psql -U user -d todo'
      interval: 3s
      timeout: 3s
      retries: 100
      start_period: 10s
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    networks:
      - custom_network
    restart: always

  server:
    build: .
    ports:
      - '9060:8080'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - custom_network

networks:
  custom_network:
    external: true
volumes:
  postgres_data:
  pgadmin_data:
