openapi: "3.0.3"
info:
  title: TODO
  version: "1.0"
servers:
  - url: http://localhost:9060
tags:
  - name: "tasks"
    description: "TODO tasks"
paths:
  /tasks:
    get:
      tags:
        - "tasks"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Tasks"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"

    put:
      tags:
        - "tasks"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TasksList"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"

    post:
      tags:
        - "tasks"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"

    delete:
      tags:
        - "tasks"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TasksList"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"

components:
  schemas:
    Task:
      title: task request body
      type: object
      properties:
        name:
          type: string
          description: task name
          default: ""
        status:
          type: integer
          description: task status
        created_at:
          type: string
          format: date-time
    Tasks:
      title: tasks body
      type: object
      properties:
        ids:
          type: array
          items:
            type: integer
        limit:
          type: integer
        offset:
          type: integer
    TasksList:
      title: tasks body
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          limit:
            type: integer
          offset:
            type: integer

    BadRequest:
      title: bad request
      type: object
      properties:
        message:
          type: string
          default: "The API request was invalid or malformed, so the API server could not understand it."
        status:
          type: integer
          description: HTTP status code of the error
      required:
        - message
        - status

    Message:
      type: object
      properties:
        message:
          type: string
          default: "OK"
